version: '3.9'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.prod  # Використовуємо продакшн Dockerfile
    command: >
      sh -c "npx sequelize-cli db:migrate --env production && npm start"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=time_craft_db
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always  # Забезпечує перезапуск бази даних у разі збою
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: time_craft_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod  # Використовуємо продакшн Dockerfile
    ports:
      - "80:80"  # Продакшн сервер зазвичай працює на порту 80
    depends_on:
      - app

volumes:
  postgres_data: