version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: time_craft_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_USER: admin
      DB_PASSWORD: root
      DB_NAME: time_craft_db
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    depends_on:
      - app

  migrate:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: npx sequelize-cli db:migrate --env production
    environment:
      PORT: 4000
      DB_USER: admin
      DB_PASSWORD: root
      DB_NAME: time_craft_db
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: