version: '3.9'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.prod  
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=time_craft_db
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: time_craft_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod 
    ports:
      - "80:80" 
    depends_on:
      - app

volumes:
  postgres_data: